back/MyProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/pages/', include('pages.urls')),
    path('api/accounts/', include('dj_rest_auth.urls')),
    path('api/accounts/signup/', include('dj_rest_auth.registration.urls')),
    # path('accounts/', include('accounts.urls')),
]

back/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

]

back/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/detail/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path("<int:article_pk>/delete/", views.delete, name="delete"),
    # api
    path('articles/', views.article_list),
    path('articles/<int:article_pk>/', views.article_detail)
]

back/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

# AbstractUser를 상속받는 커스텀 User 클래스 작성
# 기존의 User클래스도 AbstractUser를 상속받기 때문에 
# 커스텀 User 클래스도 완전히 같은 모습을 가지게 됨

class User(AbstractUser):
    pass

back/pages/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    write_date = models.DateField()
    updated_date = models.DateField(auto_now=True)
    created_date = models.DateField(auto_now_add=True)

back/pages/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    title = forms.CharField(max_length=30)
    content = forms.CharField(widget=forms.Textarea())
    write_date = forms.DateField()

    title.widget.attrs.update({'style': 'width:51.7rem; background-color :#C0DEFF; border:none; border-radius:2px', 'placeholder': '[BOJ]000_제목'})
    content.widget.attrs.update({'style': 'width: 50rem; height: 30rem; background-color :#C0DEFF; border:none; border-radius:4px','placeholder': '내용'})
    write_date.widget.attrs.update({'placeholder': '2022-12-19'})
    class Meta:
        model = Article
        fields = '__all__'
        

back/accounts/views.py
from django.shortcuts import render

# Create your views here.

back/pages/views.py
from django.shortcuts import render,redirect
from django.views.decorators.http import require_http_methods,require_safe,require_POST
from .forms import ArticleForm
from .models import Article
from .serializer import ArticleSerializer

# Build RESTful API
from rest_framework.response import Response
from rest_framework.decorators import api_view

# 성공시 201 Created, 실패시 400 Bad request
from rest_framework import status

# Permission
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated 


# Create your views here.

@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    } 
    return render(request, 'pages/index.html', context)

@require_http_methods(['GET','POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pages:index')
    else:
        form = ArticleForm()
    context = {
        'form': form
    }
    return render(request, 'pages/create.html', context)

@require_safe
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    context = {
        'article': article
    }
    return render(request, 'pages/detail.html', context)

@require_http_methods(['GET','POST'])
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST,instance=article)
        if form.is_valid():
            form.save()
            return redirect('pages:detail', article_pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form
    }
    return render(request, 'pages/update.html', context)


def delete(request,article_pk):
    article = Article.objects.get(pk=article_pk)
    article.delete()
    return redirect('pages:index')


@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
def article_list(request):
    if request.method == "GET":
        articles = Article.objects.all()
        # many=True 를 작성하는 이유는 여러개의 경우기 때문
        serializer = ArticleSerializer(articles, many=True)
        # render가 아닌 Response를 사용하여 
        # JSON 데이터를 DRF 전용 템플릿으로 응답
        return Response(serializer.data)
    elif request.method == "POST":
        serializer = ArticleSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        


@api_view(['GET','DELETE', 'PUT'])
@permission_classes([IsAuthenticated])
def article_detail(request,article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == "GET":
        serializer = ArticleSerializer(article)
        return Response(serializer.data)
    elif request.method == 'DELETE':
        article.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    elif request.method == "PUT":
        serializer = ArticleSerializer(article, data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data)

back/pages/templates/pages/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>여기는 생성 페이지</h1>

  <form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
  </form>
{% endblock content %}

back/pages/templates/pages/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      width: 60%;
      padding: 0 20%;
      margin: 0;
    }
    

    #article > pre {
      padding: 2rem 0;
      display: flex;
      justify-content: center;
      align-items: center;
      background-color: black;
      color: white;
    }

    #title {
      margin-left: 10px;
      font-size: 2rem;
      font-weight: 900;
    }

    #date {
      font-size: 0.7rem;
    }

    section + article {
      margin-top: 5rem;
      background-color: bisque;
    }

    a {
      text-decoration: none;
      color: cadetblue;
      font-weight: 400;
    }

    a:hover {
      color: darkolivegreen;
    }
  </style>
  <title>Document</title>
</head>
<body >
  <section>
    <h1>✔</h1>
  </section>
  <article>
    <div id="article">
      <div id="title">{{article.title}}</div>
      <span id="date">{{article.write_date}}</span>
      <pre>{{article.content}}</pre>
      <a href="{% url 'pages:update' article.pk %}">게시글 수정 / </a>
      <a href="{% url 'pages:delete' article.pk %}">게시글 삭제</a>
    </div>
  </article>

  

  <a href="{% url 'pages:index' %}">메인페이지</a>
</body>
</html>

back/pages/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>여기는 인덱스 페이지</h1>
  <a href="{% url 'pages:create' %}"> 생성하기</a>
  <hr>

  {% if articles %}
  {% for article in articles  %}
    <a href="{% url 'pages:detail' article.pk %}">
      <p>{{article.title}}</p>
    </a>
    <hr>
  {% endfor %}
  {% else %}
    <p>게시글을 작성해주세요 :)</p>
  {% endif %}
{% endblock content %}

back/pages/templates/pages/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>수정 페이지</h1>
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정">
  </form>
{% endblock content %}

back/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    a {
      text-decoration: none;
      color: cadetblue;
      font-weight: 400;
    }

    a:hover {
      color: darkolivegreen;
    }

    body {
      width: 60%;
      padding: 0 20%;
      margin: 0;
    }
  </style>
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>